name: Deploy to Dev

on:
  push: 
    branches:
      - develop
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    environment: Development
    permissions:
      checks: write
      contents: write      
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Setup .NET        
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version: '9.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Debug 

      - name: Publish the application
        run: dotnet publish ".\TenEightVideo.Web.Services\TenEightVideo.Web.Services.csproj" -c Debug -o ${{ github.workspace }}/publish_output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapi-publish-profile
          path: ${{ github.workspace }}/publish_output
                 
  deploy:
    needs: build
    runs-on: self-hosted
    environment: Development
    env:
      ConnectionStrings__TenEightVideo: ${{ secrets.CONNECTION_STRING }}
    
    steps:      

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapi-publish-profile
          path: C:\inetpub\develop.services.10-8video.com
