name: Deploy to Dev

on:
  push: 
    branches:
      - develop
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    environment: Development
    env:
      ConnectionStrings__TenEightVideo: ${{ secrets.CONNECTION_STRING }}
    permissions:
      checks: write
      contents: write      
      
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean previous build artifacts and untracked files
        # This command removes all untracked files and directories.
        run: git clean -fdxq

      # We can safely assume .NET is already installed
      #- name: Setup .NET        
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version: '9.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Debug

      - name: Publish the application
        run: dotnet publish --configuration Debug --output ./publish_output
                 
  deploy:
    needs: build
    runs-on: self-hosted
    environment: Development    
    
    steps:      
            
      - name: Copy build output to target folder
        shell: cmd
        run: |
          robocopy ./publish_output/ "\inetpub\develop.services.10-8video.com" /e /zb /copyall /purge /dcopy:da /NFL /NDL /NP /NS /NC
          IF %ERRORLEVEL% LEQ 7 (exit 0) ELSE (exit 1)      
      
         

      
